name: ml1m_llmrank
root_dir: ../llmrank/data
dataset_dir_name: ml-1m
atomic_subdir: atomic
source_format: single_inter
interactions_filename: ml-1m.inter
item_filename: ml-1m.item
candidate_filename: ml-1m.bm25
candidate_budget: 20
use_external_candidates_for_valid: false
drop_missing_candidate_users: true
split:
  strategy: leave_one_out
  order: chronological
  per_user: true
  valid_holdout_num: 1
  test_holdout_num: 1
